name: Antonio De Palma
favicon: null
layout_spectrum: 0
typography_spectrum: 0.68053
title: "Let's think about it..."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-13098980-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3125
  lightness: 0.604694921290502
  saturation: 0.7939277710393071
  rhythmicContrast: 0.4501144993118942
purpose: []
